version: "3"
services:
  app:
    build:
     context: .
     dockerfile: infrastructure/docker/dockerfile-node
    volumes:
       - ./:/code
    working_dir: /code
    command: sh -c "test -d node_modules || npm install; npm serve"
    env_file: .env
    ports:
      - "3000:8080"
